### PR TITLE
Intro Text

### LINKED ISSUE #11: ROLIE Extensions - Checklist: ROLIE property list
The Checklist extension needs to list and define a well-structured enumeration of properties that are valuable to expose at the highest level to aid automation, searching, filtering, etc.

We have a draft list already, but the list needs to be expanded to cover other use cases as well.

Each member needs to investigate the important properties that they/their users need to accomplish effective searching/filtering/etc.

We also need to determine which of these properties will be mandatory, and which will be optional.

### PR DESCRIPTION
**Pull request by wmunyan**
Some minor tweaks to the introduction per #20

### CODE REVIEW

**Comment by canb227** [comment]
From conversation:
 1. We need a property field (0..n) for product name
 2. Remove publication date property
 3. Switch underscore to hyphen
 4. Wonky Quotes (angled -> straight)

**Comment by redhatrises** [comment]
@wmunyan any updates on this PR? It now needs a rebase.

**Comment by wmunyan** [comment]
@redhatrises @canb227 Do you guys want to take a look at this before it's merged or do you just want me to go ahead and merge it.  I've done my best to resolve the conflicts from previous PRs and incorporated the changes noted in the above comments.

**Comment by stephenbanghart** [comment]
Looks good. I'm going to go ahead and merge this to get the document in before deadline. Thanks Bill.

**Pull request merged**
